chore: unset QT_QPA_PLATFORM
linuxdeepin/linglong-pica pull request #47
Opened 2024-09-02 02:16 UTC by chenchongbiao

deepin 上点击 desktop 启动应用，由于AM会继承 systemd 设置 QT_QPA_PLATFORM=dxcb变量，但是应用本身并没有该插件，需要在启动脚本中取消 QT_QPA_PLATFORM 变量

Log: unset env

2024-09-02 03:30 UTC, black-desk requested changes
我感觉不应该这么修，要不然am那边给个说法，不要固定死设置这个环境变量。
要不然这种情况应该由应用自己在自己的启动脚本里面override掉。

另外就 runtime里面需要带一个脚本，配置一些环境变量，如果应用确实在直接使用runtime提供的qt，那么应用吃到的环境变量应该是完全正确的才对。

2024-09-03 02:27 UTC, feiguoL approved these changes

2024-09-03 02:58 UTC, liujianqiang-niu approved these changes

2024-09-03 06:49 UTC, chenchongbiao commented
由 dde 和 AM 取消 dxcb 默认值。

2024-09-03 06:49 UTC, closed without merging